### ISSUE TITLE
Open graph tags

### ISSUE THREAD

**Issue by wlhtck** [will-hitchcock/mccrea-deezer-src#1]
We need to add open graph meta tags to index.html for facebook and other sharing standards. These need to be back-end generated as facebook and other scrapers will not run JS.

**Comment by Dshawne** [comment]
So how do we solve this issue? I'm confused...

**Comment by wlhtck** [comment]
You don't need to worry about this really. We do need to decide what content should be placed in the tags for sharing.

We need to choose an image, a title and a description for sharing.

**Comment by wlhtck** [comment]
Check out what we're seeing here:
https://developers.facebook.com/tools/debug/sharing/?q=mccrea-deezer.herokuapp.com

We need a creative decision on what we put in the social share data.

**Comment by Dshawne** [comment]
Confused...Let's talk in person

**Comment by Dshawne** [comment]
![graph asset](https://cloud.githubusercontent.com/assets/23664697/20855863/2b9f9456-b8d1-11e6-93cd-ec8606a0e65c.png)
