### ISSUE TITLE
Implement New Album Cover

### ISSUE THREAD

**Issue by Dshawne** [will-hitchcock/mccrea-deezer-src#12]
Need to replace album cover with higher resolution photo

**Comment by Dshawne** [comment]
Here's the album cover. If it's not high-res enough for you, the Illustrator file is in the Goggle Drive folder.
![laikigoldcover psd-07](https://cloud.githubusercontent.com/assets/23664697/20984449/49c3cdb0-bc8e-11e6-9650-d996e5e42a26.png)

**Comment by wlhtck** [comment]
This is resolved, please verify.
