### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by Dshawne** [will-hitchcock/mccrea-deezer-src#14]
They are both 28x36
![mccrea deezer logo](https://cloud.githubusercontent.com/assets/23664697/21071220/9f01f484-be67-11e6-97a2-6136665d6e30.png)

![white mccrea deezer logo](https://cloud.githubusercontent.com/assets/23664697/21071221/9f030de2-be67-11e6-9703-3ed86978554e.png)

**Comment by Dshawne** [comment]
Here's the white one
![white mccrea deezer logo](https://cloud.githubusercontent.com/assets/23664697/21071224/b7022662-be67-11e6-91be-575bd36b34ca.png)

**Comment by wlhtck** [comment]
Please review

**Comment by Dshawne** [comment]
It still looks blurry a bit...idk what's going on

**Comment by Dshawne** [comment]
Could you use a svg possibly?

**Comment by Dshawne** [comment]
See if those work and set the image size. Might be possible that me sending you the icon that small is fucking up the resolution

![black logo](https://cloud.githubusercontent.com/assets/23664697/21234869/676713a6-c2c2-11e6-80a9-c7e625499122.png)
![white logo](https://cloud.githubusercontent.com/assets/23664697/21234868/67650200-c2c2-11e6-8e50-e25bcd91cff8.png)

**Comment by Dshawne** [comment]
Files are in a zip folder
[Mccrea Deezer SVG logo files.zip](https://github.com/will-hitchcock/mccrea-deezer-src/files/655425/Mccrea.Deezer.SVG.logo.files.zip)

**Comment by Dshawne** [comment]
Yes it's good now.
