### ISSUE TITLE
Music page interaction

### ISSUE THREAD

**Issue by wlhtck** [will-hitchcock/mccrea-deezer-src#6]
Hover and active states should exist for songs on the music page.

Need creative for this.

**Comment by Dshawne** [comment]
![music page](https://cloud.githubusercontent.com/assets/23664697/20854881/a2ed078e-b8c5-11e6-9720-9777834c4c73.png)

**Comment by Dshawne** [comment]
![desktop music page](https://cloud.githubusercontent.com/assets/23664697/20854985/835aeb6a-b8c6-11e6-9ded-b82c3e13ae0e.png)
