### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by Dshawne** [will-hitchcock/mccrea-deezer-src#8]
In Mobile the navigation is wrong. Refer to the comps. Why is the logo in the mobile nav? and if there isn't 4 features, then it should just be one half Bio and one half Music

**Comment by Dshawne** [comment]
![mobile navigation header](https://cloud.githubusercontent.com/assets/23664697/20802987/bbd2370c-b7bb-11e6-8a87-843e11131d32.png)
![navigation header](https://cloud.githubusercontent.com/assets/23664697/20802990/c17361d6-b7bb-11e6-89f2-c504798d0228.png)

**Comment by Dshawne** [comment]
Here are the new navigation bars. Top one is mobile, the bottom one is desktop. If you need more, assets are in Google Drive.

**Comment by wlhtck** [comment]
I am working on the implementation of this now. Can you provide the icons is a more standard format? I will need each icon in solid white and solid black, all the images need to have the same dimensions. The height of the nav bar is exactly 46px, output files should be squares of a size less than or equal to 46px. Let me know if you have any questions.

**Comment by Dshawne** [comment]
The icons are material icons besides the McCrea Deezer logo which you have. Look up permanent identity and music. Plus the logos are in Google Drive.

**Comment by wlhtck** [comment]
Great, I'll use the material icons for bio and music. For the logo however I need both black and white.  The white icon I have is 28x36, can you provide the exact same icon in black, the icon I have is attached.

Its impossible to see, as its white on white, just click below:
![image](https://cloud.githubusercontent.com/assets/20232215/20804039/5c8172aa-b7bf-11e6-8a4b-409b33e840f4.png)

**Comment by Dshawne** [comment]
![black logo](https://cloud.githubusercontent.com/assets/23664697/20804339/83035bc2-b7c0-11e6-80e3-22e4ec93745a.png)

**Comment by will-hitchcock** [comment]
The background on this one is white, it needs to be transparent.

**Comment by wlhtck** [comment]
This can be reviewed on the demo site.

**Comment by Dshawne** [comment]
The navigation tabs are different sizes on Desktop. 
<img width="1300" alt="screen shot 2016-12-01 at 2 18 37 pm" src="https://cloud.githubusercontent.com/assets/23664697/20808587/1f1d43d2-b7d1-11e6-9de7-bf81c9913ea7.png">

**Comment by wlhtck** [comment]
Updated, please verify on demo site.

**Comment by Dshawne** [comment]
Center the icon and text in each of the groups like the comp
<img width="1297" alt="screen shot 2016-12-01 at 2 37 23 pm" src="https://cloud.githubusercontent.com/assets/23664697/20809299/b60fddd4-b7d3-11e6-8c0e-72ec713a41ed.png">

**Comment by Dshawne** [comment]
The edge of the music button in the mobile app is black and not gold.
<img width="316" alt="screen shot 2016-12-01 at 2 46 33 pm" src="https://cloud.githubusercontent.com/assets/23664697/20809769/1ac02030-b7d5-11e6-8b9f-4328b3dea6f4.png">

**Comment by wlhtck** [comment]
Please review again.

Thanks.

**Comment by Dshawne** [comment]
In the mobile comp, the icons aren't centered...

<img width="314" alt="screen shot 2016-12-01 at 3 46 54 pm" src="https://cloud.githubusercontent.com/assets/23664697/20811885/7fcf944e-b7dd-11e6-9061-30b383725137.png">

**Comment by wlhtck** [comment]
Should be fixed now. I missed a style.
