### ISSUE TITLE
Google button sizing issue

### ISSUE THREAD

**Issue by Dshawne** [will-hitchcock/mccrea-deezer-src#9]
The Google button is blocking elements in the page. Either make some text smaller or make the button smaller
<img width="1300" alt="screen shot 2016-12-01 at 2 24 01 pm" src="https://cloud.githubusercontent.com/assets/23664697/20808799/e9e9dc06-b7d1-11e6-8c78-b95c712947ec.png">
<img width="312" alt="screen shot 2016-12-01 at 2 25 40 pm" src="https://cloud.githubusercontent.com/assets/23664697/20808831/169e719e-b7d2-11e6-9ac6-ba5cf6e04e0e.png">

**Comment by Dshawne** [comment]
I resized a lot of these issues in the new compositions. Can you please refer to the new comps in the Google Drive shared folder for sizing of assets. Shouldn't take long to fix these issues...

**Comment by wlhtck** [comment]
Please review changes on the music page in desktop only.

Still working on others.

Thanks!

**Comment by wlhtck** [comment]
Please review the bio page on mobile.

Let me know if there are any other areas where this is a problem.

**Comment by Dshawne** [comment]
It's fine on the bio page in mobile. It's an issue on the music page in desktop. Also the download album button on the bottom in the mobile comp is now up in the upper part.

<img width="1048" alt="screen shot 2016-12-01 at 3 00 39 pm" src="https://cloud.githubusercontent.com/assets/23664697/20810252/015497dc-b7d7-11e6-9852-3ea7d09d0058.png">
<img width="379" alt="screen shot 2016-12-01 at 3 00 51 pm" src="https://cloud.githubusercontent.com/assets/23664697/20810253/0154c856-b7d7-11e6-9388-a4251c1d0d03.png">

**Comment by wlhtck** [comment]
Can you please open a new ticket for the other changes to the music page.

**Comment by Dshawne** [comment]
ok
